### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [Igameart/DopeFishEngine#2]
I see you have no LICENSE file for this project.  The default is copyright.  I see a copy of GPL-2.0 and a EULA so this could use clarification.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by Igameart** [comment]
Thank you very much for the suggestion. I'm new to releasing open source code. I'll be sure to get that uploaded today!
